import type { Metadata } from "next";
import { Geist, Geist_Mono, Rajdhani, Quantico } from "next/font/google";
import "./globals.css";
import ViewportHeightFix from "@/components/ViewportHeightFix";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
});

// Quantico (untuk subheading atau body)
const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quantico",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${rajdhani.variable} ${quantico.variable}`}
      >
        <ViewportHeightFix />
        {children}
      </body>
    </html>
  );
}
